-- Separate function scope keeps test locals out of the production main chunk.
__runContracts=function()
  local t,m=__test,__mock
  local function check(label,actual,expected)
    if type(expected)=="number" then
      assert(type(actual)=="number" and math.abs(actual-expected)<0.001,
             label..": expected "..tostring(expected)..", got "..tostring(actual))
    else
      assert(actual==expected,label..": expected "..tostring(expected)..", got "..tostring(actual))
    end
    local value=type(actual)=="number" and string.format("%.4f",actual) or tostring(actual)
    print("TRACE|"..label.."|"..value)
  end
  local function frame(now)
    m.now=now or (m.now+10)
    t.clearFrameCache()
  end
  local function reset()
    m.values={}; m.events={}
    t.resetSessionEvidence(); t.resetSessionStats(); frame(0)
    t.applyOptions({HeliType=1,BattRsv=20,CountSrc=1,MinFlight=30,
                    RxPackMin="6.60",RxPackMax="8.40",MotorSw=99})
  end
  local function source(name,value,current,fresh)
    m.values[name]={value=value,current=current,fresh=fresh}
    frame()
  end
  local function alert(now,pct,voice,data)
    frame(now); t.updateBatteryAlertState(pct,data~=false,voice,"fc")
  end
  reset()
  check("missing current",t.getCurr(),0)
  check("missing current validity",t.D.currentValid,false)
  source("Curr",0)
  check("live zero current",t.getCurr(),0)
  check("live zero current validity",t.D.currentValid,true)
  source("Curr",{value=41.7})
  check("source value wrapper",t.getCurr(),41.7)
  source("Curr",2001)
  check("out of range current",t.getCurr(),0)
  check("out of range current validity",t.D.currentValid,false)
  source("Curr",32,false)
  check("noncurrent rejected",t.getCurr(),0)
  check("noncurrent validity",t.D.currentValid,false)
  source("Curr",32)
  m.values.Curr.throw=true
  check("source exception rejected",t.getCurr(),0)
  source("Curr",32)
  check("source recovery",t.getCurr(),32)
  m.values.Curr.value=44
  check("one sample per frame",t.getCurr(),32)
  frame()
  check("next frame refresh",t.getCurr(),44)
  -- A noncurrent cached ID must be re-resolved on a later frame.
  reset()
  m.values.Curr={id=301}; m.values[301]={value=12}
  check("numeric sensor ID lookup",t.getCurr(),12)
  m.values[301].current=false; frame()
  check("expired ID invalid",t.getCurr(),0)
  m.values.Curr={id=302}; m.values[302]={value=13}; frame()
  check("changed sensor ID recovery",t.getCurr(),13)
  source("Vcel",3.97)
  check("Rotorflight average cell scalar",t.getCellVoltage(),3.97)
  source("Bat%",0)
  check("zero battery sensor valid",t.getBatPct(),0)
  check("zero battery validity",t.D.batteryPercentValid,true)
  source("Bat%",101)
  check("invalid battery sensor",t.getBatPct(),false)
  source("Gov",4)
  check("governor active",t.getGovState(),"ACTIVE")
  source("Gov",99)
  check("unknown governor display",t.getGovState(),"--")
  check("unknown governor invalid",t.D.govCurrentInvalid,true)
  source("Hspd",0)
  check("stopped rotor zero",t.getHeadspeed(),0)
  check("stopped rotor valid",t.D.rpmValid,true)
  source("BAT#",6)
  check("one based battery profile",t.getBattProfile(),6)
  source("BAT#",0)
  check("zero profile rejected",t.getBattProfile(),nil)
  source("tx-voltage",8000)
  check("transmitter millivolts",t.getTxVolt(),8)
  check("LiPo empty",t.txPctFromVolts(7,false),0)
  check("LiIon empty",t.txPctFromVolts(6.2,true),0)
  check("transmitter full",t.txPctFromVolts(8.4,true),100)
  check("RSSI conversion",t.signalPercent(-80),50)

  -- Assert selector authority independently of UI smoothing and source cache.
  local p,valid,kind=t.selectFlightBatteryPercent(1,72,true,95,true,true)
  check("Smart Fuel priority",p,72); check("Smart Fuel source",kind,"fc")
  p,valid,kind=t.selectFlightBatteryPercent(1,72,true,nil,false,false)
  check("positive percent independent",valid,true)
  p,valid,kind=t.selectFlightBatteryPercent(1,0,true,nil,false,false)
  check("USB only is no data",valid,false)
  p,valid,kind=t.selectFlightBatteryPercent(1,0,true,nil,false,true)
  check("powered empty pack",p,0); check("powered empty pack valid",valid,true)
  p,valid,kind=t.selectFlightBatteryPercent(1,false,false,35,true,true)
  check("voltage fallback",p,35); check("voltage fallback source",kind,"voltage")
  p,valid,kind=t.selectFlightBatteryPercent(2,72,true,95,true,true)
  check("Nitro no flight percentage",valid,false)
  p,valid,kind=t.selectFlightBatteryPercent(3,72,true,nil,false,false)
  check("OMP requires pack contract",valid,false)
  check("reserve maps usable range",t.calculateAdjustedPercent(60,20),50)
  check("reserve floor",t.calculateAdjustedPercent(10,20),0)
  check("reserve full",t.calculateAdjustedPercent(100,20),100)
  reset(); source("Bat%",72); t.tick(m.now)
  check("Smart Fuel display",t.A.displayPercent,65)
  source("Bat%",60); t.tick(m.now)
  check("Smart Fuel display no second filter",t.A.displayPercent,50)
  reset(); t.OPT.heliType=3; m.modelName="My m1 heli"
  source("RxBt",8.6)
  check("OMP M1 cells",t.getCellCount(),2)
  check("OMP M1 chemistry",t.D.isLiHV,true)
  check("OMP M1 cell voltage",t.getCellVoltage(),4.3)
  m.modelName="My M2 heli"; frame()
  check("OMP M2 cells",t.getCellCount(),3)
  m.modelName="Unidentified OMP"; frame()
  check("unidentified OMP cells",t.getCellCount(),0)
  m.modelName="Fixture"

  reset(); t.A.linkAvailable=true
  alert(0,60,true); alert(10,50,true)
  check("50 percent voice",m.events[1],"voice:50")
  alert(20,40,true)
  check("voice cooldown",#m.events,1)
  alert(230,40,true)
  check("40 percent voice",m.events[2],"voice:40")
  alert(450,15,true)
  check("skipped threshold chooses lowest",m.events[3],"voice:20")
  alert(670,10,true); t.updateBatteryHapticTick()
  check("10 percent voice",m.events[4],"voice:10")
  check("low haptic first burst",m.events[5],"haptic:15")
  check("haptic immediate priority",m.hapticFlags,16)
  frame(769); t.updateBatteryHapticTick()
  check("haptic spacing",#m.events,5)
  frame(770); t.updateBatteryHapticTick()
  check("low haptic second burst",m.events[6],"haptic:15")
  frame(1000); t.updateBatteryHapticTick()
  check("only two low bursts",#m.events,6)
  alert(1010,0,true); t.updateBatteryHapticTick()
  check("zero percent voice",m.events[7],"voice:0")
  check("zero haptic starts",m.events[8],"haptic:15")
  check("zero warning latched",t.A.battZeroReached,true)
  t.voice.available[t.voice.deadPath]=true
  t.A.motorSwitchPosition=-1
  frame(1260); t.voice.updateDead(true)
  check("dead voice after initial delay",m.events[9],"file:dead.wav")
  t.A.motorSwitchPosition=1; frame(1480); t.voice.updateDead(true)
  check("switch acknowledges repeat",t.A.flightDeadVoiceAcknowledged,true)
  check("acknowledged voice stopped",#m.events,9)
  alert(1600,80,true); alert(1700,80,true)
  check("new FC battery rearms",t.A.battZeroReached,false)
  alert(1920,50,true)
  check("new battery voice",m.events[10],"voice:50")
  reset(); t.A.linkAvailable=true
  alert(0,60,false); alert(10,40,false); alert(250,40,true)
  check("enabling voice no backlog",#m.events,0)
  alert(500,30,true,false)
  check("missing sample no voice",#m.events,0)
  alert(510,30,true)
  check("voice after valid recovery",m.events[1],"voice:30")
  reset(); t.A.linkAvailable=true; t.A.battConnectionZeroPending=true
  alert(0,0,false); alert(299,0,false)
  check("startup zero waits for confirmation",t.A.battAlert0HapticPlayed,false)
  alert(300,0,false,false)
  check("startup zero gap clears evidence",t.A.battConnectionZeroSince,nil)
  alert(310,0,false); alert(609,0,false)
  check("startup zero new confirmation window",t.A.battAlert0HapticPlayed,false)
  alert(610,0,false)
  check("startup zero confirmed haptic",t.A.battAlert0HapticPlayed,true)

  reset(); t.A.linkAvailable=true
  frame(0); t.updateEscBecAlerts(111,true,4.7,true)
  frame(49); t.updateEscBecAlerts(111,true,4.7,true)
  check("ESC BEC confirmation delay",#m.events,0)
  frame(50); t.updateEscBecAlerts(111,true,4.7,true)
  check("ESC BEC confirmed",#m.events,2)
  frame(150); t.updateEscBecAlerts(105,true,4.9,true)
  check("ESC BEC hysteresis",#m.events,2)
  frame(200); t.updateEscBecAlerts(99,true,5.1,true)
  check("ESC rearmed",t.A.escTempAlertPlayed,false)
  check("BEC rearmed",t.A.becAlertPlayed,false)
  frame(250); t.updateEscBecAlerts(111,true,4.7,true)
  frame(280); t.updateEscBecAlerts(111,false,4.7,false)
  frame(300); t.updateEscBecAlerts(111,true,4.7,true)
  frame(349); t.updateEscBecAlerts(111,true,4.7,true)
  check("invalid sample resets persistence",#m.events,2)
  frame(350); t.updateEscBecAlerts(111,true,4.7,true)
  check("alerts recur after rearm",#m.events,4)

  reset(); t.A.linkAvailable=true; t.A.motorSwitchPosition=-1
  frame(0); t.updateRxPackAlert(6.6)
  frame(199); t.updateRxPackAlert(6.6)
  check("Nitro qualification",#m.events,0)
  frame(200); t.updateRxPackAlert(6.6)
  check("Nitro sustained low",t.A.rxDeadVoiceLatched,true)
  check("Nitro low haptic",#m.events,1)
  t.A.motorSwitchPosition=1; frame(220); t.updateRxPackAlert(6.6)
  check("Nitro acknowledgement",t.A.rxDeadVoiceAcknowledged,true)
  check("Nitro acknowledgement stops haptic",#m.events,1)
  frame(230); t.updateRxPackAlert(7.0)
  check("Nitro recovered rearm",t.A.rxDeadVoiceLatched,false)

  reset()
  local opts={Theme=1,TxBatt=1,HeliType=1,BattRsv=20,CountSrc=1,MinFlight=30,
              RxPackMin="6.60",RxPackMax="8.40",MotorSw=99}
  local w=t.create({x=0,y=0,w=800,h=480},opts)
  local function count(start,value)
    m.timer={start=start,value=value}; frame(); t.tickFlightCount()
    return t.getFlightCount()
  end
  check("count initial",count(0,0),0)
  check("count before ascending threshold",count(0,29),0)
  check("count at ascending threshold",count(0,30),1)
  check("count only once per cycle",count(0,80),1)
  check("count reset rearms",count(0,0),1)
  check("count second ascending cycle",count(0,30),2)
  check("count countdown starts",count(120,120),2)
  check("count before countdown threshold",count(120,91),2)
  check("count at countdown threshold",count(120,90),3)
  check("count countdown overrun",count(120,-10),3)
  w=t.create({x=0,y=0,w=800,h=480},opts)
  check("attach over threshold no extra flight",count(120,80),3)
  check("attach then reset",count(120,120),3)
  check("attach next flight",count(120,90),4)
  check("malformed timer",t.timerElapsedSeconds({value="bad"}),nil)
  check("timer elapsed clamped",t.timerElapsedSeconds({start=120,value=130}),0)

  local names={"Theme","TxBatt","MinFlight","HeliType","BattRsv","BattVoice",
               "RxPackMin","RxPackMax","MotorSw","CountSrc"}
  check("persisted option count",#t.options,10)
  for i,name in ipairs(names) do check("option slot "..i,t.options[i][1],name) end
  check("default counter",t.options[10][3],2)
  t.applyOptions({MinFlight=-30,BattRsv=99,CountSrc=99,RxPackMin="66",RxPackMax="840"})
  check("legacy negative duration",t.config(),30)
  check("reserve clamped",t.OPT.reservePct,50)
  check("invalid counter defaults FC",t.OPT.flightCounter,2)
  check("legacy Rx tenths",t.OPT.rxPackMin,6.6)
  check("legacy Rx hundredths",t.OPT.rxPackMax,8.4)
  check("Rx settings validity",t.OPT.rxPackValid,true)
  t.applyOptions(opts)
  t.A.battZeroReached=true; t.A.rxDeadVoiceLatched=true; t.S.rpmMax=2300
  opts.Theme=2; t.update(w,opts)
  check("theme preserves flight warning",t.A.battZeroReached,true)
  check("theme preserves Nitro warning",t.A.rxDeadVoiceLatched,true)
  check("theme preserves session maximum",t.S.rpmMax,2300)
  opts.BattRsv=25; t.update(w,opts)
  check("reserve resets flight warning",t.A.battZeroReached,false)
  check("reserve preserves Nitro warning",t.A.rxDeadVoiceLatched,true)
  opts.RxPackMin="6.7"; t.update(w,opts)
  check("Rx option resets Nitro warning",t.A.rxDeadVoiceLatched,false)
  t.D.currentValid=true; t.A.linkAvailable=true
  opts.HeliType=2; t.update(w,opts)
  check("type resets sensor evidence",t.D.currentValid,false)
  check("type resets link evidence",t.A.linkAvailable,false)
  check("type resets session maximum",t.S.rpmMax,0)
  for i=1,#t.options[1][4] do
    opts.Theme=i; t.applyOptions(opts)
    local bg,accent,transparent=t.theme()
    assert(transparent==(__variant=="KSE4" and (i==3 or i==19)))
    -- Palette and theme slot traces compare to the same variant's baseline.
    print("THEME|"..i.."|"..t.options[1][4][i].."|"..tostring(bg).."|"..
          tostring(accent).."|"..tostring(transparent))
  end
  check("complete",true,true)
end
__runContracts()
