#!/usr/bin/env python3
"""Assemble one authored engine and two renderers into standalone EdgeTX widgets."""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DIRECTIVE = re.compile(r"^-- @(include|module) (\S+)(?: (\w+))?$", re.M)
HEADER = "-- GENERATED by tools/assemble.py; edit src/shared or src/variants instead.\n"


def assemble(variant):
    seen = set()

    def expand(path):
        path = path.resolve()
        if path in seen:
            raise ValueError(f"Duplicate or recursive include: {path.relative_to(ROOT)}")
        seen.add(path)

        def include(match):
            kind, target, binding = match.groups()
            if kind == "module":
                if not binding:
                    raise ValueError("A module directive needs its local binding")
                body = expand(ROOT / "src/shared" / (target + ".lua"))
                return (f"-- BEGIN SHARED {target}\nlocal {binding} = (function()\n"
                        + body + f"end)()\n-- END SHARED {target}")
            scope, filename = target.split(":", 1)
            if scope not in ("shared", "variant") or Path(filename).name != filename:
                raise ValueError(f"Invalid include: {target}")
            base = ROOT / "src/shared" if scope == "shared" else ROOT / "src/variants" / variant
            body = expand(base / filename)
            return f"-- BEGIN {scope.upper()} {filename}\n" + body + f"-- END {scope.upper()} {filename}"

        return DIRECTIVE.sub(include, path.read_text())

    result = HEADER + expand(ROOT / "src/variants" / variant / "main.lua")
    required = set((ROOT / "src/shared").glob("*.lua"))
    if required - seen:
        raise ValueError(f"Unassembled shared sources for {variant}: {required - seen}")
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated outputs differ")
    args = parser.parse_args()
    stale = []
    for variant in ("KSE4", "KSE5"):
        path = ROOT / variant / "main.lua"
        updated = assemble(variant)
        if path.read_text() != updated:
            stale.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.write_text(updated)
    if stale and args.check:
        raise SystemExit("Regenerate dashboards: " + ", ".join(stale))
    print("Standalone dashboards " + ("updated: " + ", ".join(stale) if stale else "are current"))


if __name__ == "__main__":
    main()
